const action = {
  ADD_TASK: 'ADD_TASK',
  DELETE_TASK: 'DELETE_TASK',
  CHECK_TASK: 'CHECK_TASK',
  DELETE_CHECKED_TASKS: 'DELETE_CHECKED_TASKS',
  CHANGE_TASKS_ARRAY: 'CHANGE_TASKS_ARRAY',
  EDIT_TASK: 'EDIT_TASK',
  ADD_LIST: 'ADD_LIST',
  DELETE_LIST: 'DELETE_LIST',
  CHANGE_LIST: 'CHANGE_LIST',
  EDIT_LIST: 'EDIT_LIST',
  REORDER_LISTS: 'REORDER_LISTS',
}

export default action;